# Site settings
title: Querida Matemática
description: Querida Matemática
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Querida Matemática
user_description: teste
email: janaine.martins@ufv.br
twitter_username: janaineMartinss
github_username:  JanaineMath

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
